# Generated by Django 5.0 on 2024-06-01 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Benhnhan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hoten", models.CharField(max_length=100)),
                ("gioitinh", models.CharField(max_length=100)),
                ("namsinh", models.IntegerField()),
                ("diachi", models.CharField(max_length=100)),
                ("ngaykham", models.DateField(default="2024-01-01")),
            ],
        ),
        migrations.CreateModel(
            name="Thuoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenThuoc", models.CharField(max_length=50)),
                ("giatheovien", models.IntegerField()),
                ("giatheochai", models.IntegerField()),
                ("soviencon", models.IntegerField()),
                ("sochaicon", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Hoadon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tienkham", models.IntegerField()),
                ("tienthuoc", models.IntegerField()),
                (
                    "benhnhan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.benhnhan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhieuKB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trieuchung", models.CharField(max_length=100)),
                ("dudoan", models.CharField(max_length=100)),
                (
                    "benhnhan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.benhnhan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PKBthuoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donvi", models.CharField(max_length=50)),
                ("soluong", models.IntegerField()),
                ("cachdung", models.CharField(max_length=50)),
                (
                    "phieukb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.phieukb"
                    ),
                ),
                (
                    "thuoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.thuoc"
                    ),
                ),
            ],
        ),
    ]
