# Generated by Django 5.0 on 2024-06-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_patient", models.IntegerField(default=40)),
                ("cachdung", models.CharField(default="A B C D", max_length=500)),
                ("loaibenh", models.CharField(default="A B C D E", max_length=500)),
                ("tienkham", models.IntegerField(default=30000)),
            ],
        ),
    ]
