# Generated by Django 5.0.4 on 2024-06-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='thietbiYte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(choices=[('Supplier A', 'Supplier A'), ('Supplier B', 'Supplier B'), ('Supplier C', 'Supplier C'), ('Supplier D', 'Supplier D'), ('Supplier E', 'Supplier E')], max_length=200)),
                ('import_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='pkbthuoc',
            name='soluong',
            field=models.IntegerField(),
        ),
    ]
