# Generated by Django 5.0.4 on 2024-06-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_thietbiyte_alter_pkbthuoc_soluong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thietbiyte',
            name='price',
            field=models.IntegerField(),
        ),
    ]
