# Generated by Django 5.0 on 2024-06-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_defaultvalues"),
        ("myapp", "0003_alter_thietbiyte_price"),
    ]

    operations = []
