# Generated by Django 5.0.3 on 2024-06-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_baocaothuoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaoCaoThuoc',
        ),
    ]
