# Generated by Django 5.0 on 2024-06-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_merge_0002_defaultvalues_0003_alter_thietbiyte_price"),
        ("myapp", "0005_delete_baocaothuoc"),
    ]

    operations = []
